### ISSUE TITLE
Fpop not available for R version 3.6.0

### ISSUE THREAD

**Issue by as4378** [as4378/Opart-GSoC#4]
Hi @tdhock ,

https://travis-ci.org/as4378/opart/builds/551591609

Getting this error on Travis when using fpop in microbenchmark with opart_gaussian for comparing runtimes.

**Comment by tdhock** [comment]
eventually @guillemr said he would put fpop on CRAN

until then maybe you can add some code that tests for presence of fpop and only uses it in the timing if it is present?

e.g. put fpop in Suggests in DESCRIPTION

then in your code do if(requireNamespace("fpop"))
